[project]
name = "dotsys"
version = "0.1.0"
authors = [
    {name="Gabriele Beltramo", email="hello@gbeltramo.com"},
]
description = "A Python package to manage config files and general system configuration."
readme = "README.md"
requires-python = ">=3.8,<3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]

[build-system]
requires = ["setuptools>=67.0.0"]
build-backend = "setuptools.build_meta"

[tool.bumpver]
current_version = "0.1.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message  = "Bump version {old_version} -> {new_version}"
commit          = true
tag             = true
push            = false


[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']
"Makefile" = ['VERSION := {version}']
